# Generated by Django 5.1.2 on 2024-11-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_verification_code_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
