# Generated by Django 5.1.2 on 2024-10-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vital_events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VitalEvent',
            new_name='BirthCertificate',
        ),
    ]
