# Generated by Django 5.1.2 on 2024-10-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_events', '0002_rename_vitalevent_birthcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthcertificate',
            name='application_number',
            field=models.CharField(default=123456, editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
