# Generated by Django 5.1.2 on 2024-10-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_events', '0003_birthcertificate_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificate',
            name='application_number',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
