# Generated by Django 5.1.2 on 2024-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_events', '0005_birthcertificate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthcertificate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
