# Generated by Django 5.1.2 on 2024-11-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_events', '0006_birthcertificate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthcertificate',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
