# Generated by Django 5.1.2 on 2024-11-11 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_events', '0007_birthcertificate_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthcertificate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
